// Admin-gated Four.meme launch orchestrator.
// Reads from fourMemeTokenLauncher which hardcodes Niya Labs' own
// EIP-8004 agent identity. Forkers: see docs/PUBLIC_CONTRACTS.md before
// running this endpoint against your own wallet.

import type { NextApiRequest, NextApiResponse } from 'next';
import {
  verifyAgentWallet,
  runFullLaunchPreparation,
  registerEIP8004Agent,
  authenticateWithFourMeme,
  uploadNiyaImage,
  createTaxToken,
  fetchPublicConfig,
  LAUNCH_CONFIG,
} from '@/features/trading/fourMemeTokenLauncher';
import { ethers } from 'ethers';
import { createHash } from 'crypto';
import { timingSafeEqualStr } from '@/features/auth/timingSafeEqual';
import { verifyAdminSession } from '@/features/auth/adminSession';
import { enforceRateLimit } from '@/features/auth/rateLimit';
import { storage } from '../../../../server/storage';

const TOKEN_MANAGER2_ADDRESS = '0x5c952063c7fc8610FFDB798152D69F0B9550762b';
const TOKEN_MANAGER2_ABI = [
  {
    inputs: [
      { internalType: 'bytes', name: 'createArg', type: 'bytes' },
      { internalType: 'bytes', name: 'sign', type: 'bytes' },
    ],
    name: 'createToken',
    outputs: [],
    stateMutability: 'payable',
    type: 'function',
  },
];

function checkAdminAuth(req: NextApiRequest): boolean {
  const secret = req.headers['x-admin-secret'];
  const expected = process.env.ADMIN_SECRET;
  if (typeof secret !== 'string' || !expected) return false;
  return timingSafeEqualStr(secret, expected);
}

// Endpoint identifiers for the shared rate_limits table. We reuse the table
// for idempotency (instead of adding a dedicated table) because Drizzle
// checkAndConsumeRateLimit with limit=1 already gives us exactly-once
// semantics for free: the first caller consumes the only slot, any replay
// within the window is rejected atomically.
const LAUNCH_RL_ENDPOINT = 'admin/four-meme-launch';
const IDEMPOTENCY_ENDPOINT = 'four-meme-launch:idempotency';
const IDEMPOTENCY_WINDOW_MS = 24 * 60 * 60 * 1000; // 24 hours

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  // Phase 1.2 — cookie-first, legacy x-admin-secret header as fallback.
  const sessionValid = await verifyAdminSession(req);
  if (!sessionValid && !checkAdminAuth(req)) {
    return res.status(401).json({ error: 'Unauthorized — invalid or missing admin credentials' });
  }

  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed. Use POST.' });
  }

  // Per-IP rate limit: 1 launch per 10 minutes. Launching a token burns real
  // BNB (dev buy + gas). Apply after auth so anonymous callers can't drain
  // the admin's quota.
  const rl = await enforceRateLimit(req, res, {
    endpoint: LAUNCH_RL_ENDPOINT,
    limit: 1,
    windowMs: 600_000,
  });
  if (!rl.allowed) return; // 429 already written

  const { action } = req.body;

  // Idempotency / replay guard. Any mutating action (i.e. anything other
  // than the read-only `config` probe) runs through this. We reuse the
  // rate_limits table with a dedicated endpoint identifier and limit=1 so
  // the first request consumes the slot atomically; any subsequent request
  // with the same key within 24h gets rejected.
  //
  // Client may pass `idempotencyKey` in the body (preferred: a UUID
  // generated by the UI). If absent, we derive a deterministic SHA-256 hash
  // of the request body so accidental double-clicks (same body, no key) are
  // still caught. The hash-fallback means two legitimately different
  // launches won't collide, but two identical submits will.
  if (action && action !== 'config') {
    const clientKey: string | undefined =
      typeof req.body?.idempotencyKey === 'string' ? req.body.idempotencyKey : undefined;
    const idKey =
      clientKey && clientKey.length > 0
        ? clientKey
        : `body:${createHash('sha256').update(JSON.stringify(req.body ?? {})).digest('hex')}`;

    try {
      const idCheck = await storage.checkAndConsumeRateLimit(
        idKey,
        IDEMPOTENCY_ENDPOINT,
        IDEMPOTENCY_WINDOW_MS,
        1,
      );
      if (!idCheck.allowed) {
        return res.status(409).json({ error: 'Duplicate request — idempotency key replayed' });
      }
    } catch (e: any) {
      // Fail-open: if the DB is unreachable we don't want to brick the
      // admin UI. The upstream rate limit still caps abuse at 1 per 10min.
      console.warn('[four-meme-launch] idempotency check failed, allowing:', e?.message ?? e);
    }
  }

  const walletAddress = process.env.BNB_WALLET_ADDRESS;
  const privateKey = process.env.BNB_PRIVATE_KEY;

  if (!walletAddress) {
    return res.status(500).json({ error: 'BNB_WALLET_ADDRESS environment variable not set.' });
  }

  if (action === 'config') {
    const hasPrivateKey = !!privateKey;
    return res.status(200).json({
      success: true,
      config: LAUNCH_CONFIG,
      system: {
        walletAddress,
        hasPrivateKey,
        privateKeyWarning: hasPrivateKey
          ? null
          : 'BNB_PRIVATE_KEY is not set. Add it to Replit Secrets to enable token launch.',
        contractAddresses: {
          tokenManager2: '0x5c952063c7fc8610FFDB798152D69F0B9550762b',
          agentIdentifier: '0x09B44A633de9F9EBF6FB9Bdd5b5629d3DD2cef13',
          eip8004Registry: '0x8004A169FB4a3325136EB29fA0ceB6D2e539a432',
        },
      },
    });
  }

  if (action === 'verify-agent') {
    try {
      const result = await verifyAgentWallet(walletAddress);
      return res.status(200).json({ success: true, ...result });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || 'Agent verification failed' });
    }
  }

  if (action === 'register-8004') {
    if (!privateKey) {
      return res.status(400).json({
        error: 'BNB_PRIVATE_KEY is required to register the EIP-8004 identity NFT.',
      });
    }
    try {
      const imageUrl = req.body.imageUrl || '';
      const result = await registerEIP8004Agent(
        privateKey,
        'Niya',
        imageUrl,
        'Niya is an AI companion on BNB Chain. Candy-loving crypto friend powered by DGrid AI Gateway.'
      );
      return res.status(200).json({ success: true, ...result });
    } catch (err: any) {
      return res.status(500).json({
        error: err.message || 'EIP-8004 registration failed',
        detail: String(err),
      });
    }
  }

  if (action === 'prepare') {
    if (!privateKey) {
      return res.status(400).json({
        error:
          'BNB_PRIVATE_KEY is required to authenticate with four.meme. Add it to your Replit Secrets.',
      });
    }

    try {
      const result = await runFullLaunchPreparation(walletAddress, privateKey);
      return res.status(200).json({ success: true, ...result });
    } catch (err: any) {
      return res.status(500).json({
        error: err.message || 'Launch preparation failed',
        detail: String(err),
      });
    }
  }

  if (action === 'get-nonce') {
    try {
      const nonceRes = await fetch('https://four.meme/meme-api/v1/private/user/nonce/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ accountAddress: walletAddress, verifyType: 'LOGIN', networkCode: 'BSC' }),
      });
      const nonceData = await nonceRes.json();
      if (nonceData.code !== '0' && nonceData.code !== 0) {
        return res.status(500).json({ error: `Nonce failed: ${nonceData.msg || JSON.stringify(nonceData)}` });
      }
      const nonce = nonceData.data as string;
      return res.status(200).json({
        success: true,
        nonce,
        message: `You are sign in Meme ${nonce}`,
        walletAddress,
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || 'Failed to get nonce' });
    }
  }

  if (action === 'prepare-metamask') {
    const { signature: browserSignature, walletOverride } = req.body;
    if (!browserSignature) {
      return res.status(400).json({ error: 'signature is required (browser MetaMask signature)' });
    }
    const usedWallet = walletOverride || walletAddress;
    try {
      const loginRes = await fetch('https://four.meme/meme-api/v1/private/user/login/dex', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          region: 'WEB',
          langType: 'EN',
          loginIp: '',
          inviteCode: '',
          verifyInfo: {
            address: usedWallet,
            networkCode: 'BSC',
            signature: browserSignature,
            verifyType: 'LOGIN',
          },
          walletName: 'MetaMask',
        }),
      });
      const loginData = await loginRes.json();
      if (loginData.code !== '0' && loginData.code !== 0) {
        return res.status(500).json({ error: `Login failed: ${loginData.msg || JSON.stringify(loginData)}` });
      }
      const accessToken = loginData.data as string;

      const raisedToken = await fetchPublicConfig();
      const imgUrl = await uploadNiyaImage(accessToken);
      const { createArg, signature: fourMemeSignature } = await createTaxToken(
        accessToken, imgUrl, usedWallet, raisedToken
      );

      const iface = new ethers.Interface(TOKEN_MANAGER2_ABI);
      let calldata = '0x';
      try {
        calldata = iface.encodeFunctionData('createToken', [
          ethers.getBytes(createArg as `0x${string}`),
          ethers.getBytes(fourMemeSignature as `0x${string}`),
        ]);
      } catch { }

      return res.status(200).json({
        success: true,
        imgUrl,
        createArg,
        fourMemeSignature,
        txData: {
          to: TOKEN_MANAGER2_ADDRESS,
          data: calldata,
          value: '700000000000000000',
          valueDisplay: '0.7 BNB (dev buy)',
        },
      });
    } catch (err: any) {
      return res.status(500).json({ error: err.message || 'MetaMask prepare failed', detail: String(err) });
    }
  }

  return res.status(400).json({
    error: `Unknown action: "${action}". Valid actions: config, verify-agent, register-8004, prepare, get-nonce, prepare-metamask`,
  });
}
